# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('producttype', models.CharField(max_length=255)),
                ('productmodel', models.CharField(max_length=255)),
                ('productserialnumber', models.IntegerField(unique=True)),
                ('stockquantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
