# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productmodel',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productserialnumber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producttype',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockquantity',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
